### ISSUE TITLE
Won't switch back to Light mode

### ISSUE THREAD

**Issue by brhahlen** [JuanMTech/google-theme#4]
I've got the theme to switch to dark mode, but now it never switches back to light mode...

```
service: frontend.set_theme
data:
  name: "Google Theme"
  mode: light
```
